# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'R-a-dio' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for R-a-dio
  pod 'Alamofire', '3.1.0'

  target 'R-a-dioTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'R-a-dioUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end